// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: friendships.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const acceptFriendRequest = `-- name: AcceptFriendRequest :exec
UPDATE friendships
SET
  status = 'accepted',
  accepted_on = NOW()
WHERE
  id = $1
`

func (q *Queries) AcceptFriendRequest(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, acceptFriendRequest, id)
	return err
}

const getFriendRequests = `-- name: GetFriendRequests :many
SELECT
  u.id,
  u.name,
  u.email,
  u.image_url,
  f.id AS friendship_id
FROM
  friendships f
  JOIN users u ON (
    u.id = f.member1_id
    OR u.id = f.member2_id
  )
WHERE
  (
    f.member1_id = $1
    OR f.member2_id = $1
  )
  AND f.status = 'pending'
  AND u.id != $1
`

type GetFriendRequestsRow struct {
	ID           uuid.UUID
	Name         string
	Email        string
	ImageUrl     sql.NullString
	FriendshipID uuid.UUID
}

func (q *Queries) GetFriendRequests(ctx context.Context, member1ID uuid.UUID) ([]GetFriendRequestsRow, error) {
	rows, err := q.db.QueryContext(ctx, getFriendRequests, member1ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFriendRequestsRow
	for rows.Next() {
		var i GetFriendRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.ImageUrl,
			&i.FriendshipID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFriends = `-- name: GetFriends :many
SELECT
  u.id,
  u.name,
  u.email,
  u.image_url
FROM
  friendships f
  JOIN users u ON (
    u.id = f.member1_id
    OR u.id = f.member2_id
  )
WHERE
  (
    f.member1_id = $1
    OR f.member2_id = $1
  )
  AND f.status = 'accepted'
  AND u.id != $1
`

type GetFriendsRow struct {
	ID       uuid.UUID
	Name     string
	Email    string
	ImageUrl sql.NullString
}

func (q *Queries) GetFriends(ctx context.Context, member1ID uuid.UUID) ([]GetFriendsRow, error) {
	rows, err := q.db.QueryContext(ctx, getFriends, member1ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFriendsRow
	for rows.Next() {
		var i GetFriendsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.ImageUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeFriend = `-- name: RemoveFriend :exec
DELETE FROM friendships
WHERE
  (
    member1_id = $1
    AND member2_id = $2
  )
  OR (
    member1_id = $2
    AND member2_id = $1
  )
`

type RemoveFriendParams struct {
	Member1ID uuid.UUID
	Member2ID uuid.UUID
}

func (q *Queries) RemoveFriend(ctx context.Context, arg RemoveFriendParams) error {
	_, err := q.db.ExecContext(ctx, removeFriend, arg.Member1ID, arg.Member2ID)
	return err
}

const sendFriendRequest = `-- name: SendFriendRequest :one
INSERT INTO
  friendships (id, member1_id, member2_id, status)
VALUES
  ($1, $2, $3, 'pending')
RETURNING
  id, member1_id, member2_id, status, accepted_on, created_at, updated_at
`

type SendFriendRequestParams struct {
	ID        uuid.UUID
	Member1ID uuid.UUID
	Member2ID uuid.UUID
}

func (q *Queries) SendFriendRequest(ctx context.Context, arg SendFriendRequestParams) (Friendship, error) {
	row := q.db.QueryRowContext(ctx, sendFriendRequest, arg.ID, arg.Member1ID, arg.Member2ID)
	var i Friendship
	err := row.Scan(
		&i.ID,
		&i.Member1ID,
		&i.Member2ID,
		&i.Status,
		&i.AcceptedOn,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
