// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Friendship struct {
	ID         uuid.UUID
	Member1ID  uuid.UUID
	Member2ID  uuid.UUID
	Status     string
	AcceptedOn sql.NullTime
	CreatedAt  time.Time
	UpdatedAt  sql.NullTime
}

type Match struct {
	ID              uuid.UUID
	MatchDate       time.Time
	DurationMinutes int32
	CreatedBy       uuid.UUID
	Team1Score      int32
	Team1Player1    uuid.UUID
	Team1Player2    uuid.NullUUID
	Team2Score      int32
	Team2Player1    uuid.NullUUID
	Team2Player2    uuid.NullUUID
	CreatedAt       time.Time
	UpdatedAt       sql.NullTime
}

type User struct {
	ID        uuid.UUID
	Name      string
	Email     string
	ImageUrl  sql.NullString
	CreatedAt time.Time
	UpdatedAt sql.NullTime
}
